#!/usr/bin/env bash

function into_ansible {
  jq "$(cat "$shome/exec/inventory-aws.jq")"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aws ec2 describe-instances | into_ansible
}

source sub-chain "$BASH_SOURCE" "$@"
