#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_table="fogg_inventory"
  local nm_item="$1"; shift

  aws dynamodb delete-item \
    --table "$nm_table" \
    --key "$(jq -n --arg item "$nm_item" '{Item: { S: $item}}')" \
    --condition-expression '#item = :item' \
    --expression-attribute-names "$(jq -n '{"#item": "Item"}')" \
    --expression-attribute-values "$(jq -n --arg item "$nm_item" '{":item": {S: $item}}')"
}

source sub "$BASH_SOURCE" "$@"
