#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_table="fogg_inventory"
  local nm_item="$1"; shift
  local nm_tag="$1"; shift
  local val_tag="$1"; shift

  aws dynamodb update-item \
    --table "$nm_table" \
    --key "$(jq -n --arg item "$nm_item" '{Item: { S: $item}}')" \
    --update-expression 'set #tag = :tag' \
    --condition-expression '#item = :item' \
    --expression-attribute-names "$(jq -n --arg tag "$nm_tag" '{"#item": "Item", "#tag": $tag}')" \
    --expression-attribute-values "$(jq -n --arg item "$nm_item" --arg tag "$val_tag" '{":item": {S: $item}, ":tag": {S: $tag}}')"
}

source sub "$BASH_SOURCE" "$@"
