#!/usr/bin/env bash

function into_ansible {
  jq "$(cat "$shome/exec/inventory-aws.jq")"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "${1:-}" == - ]]; then
    cat
  else
    aws ec2 describe-instances | jq '[ .Reservations[].Instances[] ]'
  fi | into_ansible
}

source sub-chain "$BASH_SOURCE" "$@"
