#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_table="fogg_inventory"
  export cidr_network="$1"; shift

  runmany 1 2 'inventory stock $1 cidr "$cidr_network" netbits $2 ' "$@"
}

source sub "$BASH_SOURCE" "$@"
