#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_table="fogg_inventory"
  local nm_item="$1"; shift
  local nm_bywhom="${1:-yes}"

  aws dynamodb update-item \
    --table "$nm_table" \
    --key "$(jq -n --arg item "$nm_item" '{Item: { S: $item}}')" \
    --update-expression 'set Taken = :taken' \
    --condition-expression '#item = :item AND attribute_not_exists(#taken)' \
    --expression-attribute-names "$(jq -n '{"#item": "Item", "#taken": "Taken"}')" \
    --expression-attribute-values "$(jq -n --arg item "$nm_item" --arg taken "$nm_bywhom" '{":item": {S: $item}, ":taken": { S: $taken}}')"
}

source sub "$BASH_SOURCE" "$@"
