#!/usr/bin/env bash

function into_ansible {
  jq -n --arg hostname "$(uname -n)" "$(cat "$shome/exec/inventory-localhost.jq")"
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  into_ansible
}

source sub-chain "$BASH_SOURCE" "$@"
