#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  aws ec2 describe-instances | jq '.Reservations[].Instances | map({key: .PrivateIpAddress, value: with_entries(select(.value | type as $v | ["string", "boolean", "number"] | any($v == .))) }) | from_entries' | jq '{_meta: {hostvars: . }}'
}

source sub-chain "$BASH_SOURCE" "$@"
