#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local nm_table="fogg_inventory"
  local nm_category="$1"; shift
  local val_category="$1"; shift
  local nm_search="$1"; shift
  local val_search="$1"; shift

  aws dynamodb scan \
    --table "$nm_table" \
    --filter-expression 'attribute_not_exists(#taken) AND #category = :category AND #search = :search' \
    --expression-attribute-names "$(jq -n --arg category "$nm_category" --arg search "$nm_search" '{"#taken": "Taken", "#category": $category, "#search": $search}')" \
    --expression-attribute-values "$(jq -n --arg category "$val_category" --arg search "$val_search" '{":category": {S: $category}, ":search": {S: $search}}')"
}

source sub "$BASH_SOURCE" "$@"
