#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$shome/vendor/virtualenv/bin/python" ]]; then
    return 0
  fi

  return 1
}

source sub "$0" "$@"
