#!/usr/bin/env bash

function _inventory_profile {
  local shome="${_inventory_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
}

_inventory_profile
